- frontend/src/pages/about/about.jsx
Description:
The current About page is functional but could benefit from a more modern and responsive design. Suggestions include:
Implementing a gradient background for a cleaner look.
Wrapping each section in cards with shadows and subtle hover effects for better readability.
Improving typography: larger headings, better spacing, and line-height for content.
Using a responsive grid layout to optimize the display on mobile and desktop.
Adding subtle visual cues, such as colored borders for section titles, to guide the user.
> Improve About page design and responsiveness

- frontend/src/pages/profile/deleteProfile.jsx
- frontend/src/pages/profile/editProfile.jsx
- frontend/src/pages/profile/profile.jsx
This PR introduces progress on the user profile page, including initial UI improvements and updates to layout components.
- Added basic profile layout
- Improved UI with Tailwind styles
- Prepared structure for future profile features
Linked to #42 (but does not close it).
> feat(profile): progress on user profile page (ref #42)

- backend/src/models/userModels.js
- backend/src/validators/userValidators.js
- frontend/src/pages/auth/signIn.jsx
- frontend/src/pages/auth/signUp.jsx
- frontend/src/pages/profile/profile.jsx
This pull request introduces several improvements and new features across the TerraQuake application:
**Backend / User Model & Validation:**
- Added `terms`, `student`, and `experience` fields to the User model
- Updated user signup validation to include the new fields
- Ensured Terms & Conditions checkbox is properly validated
**Frontend / SignUp Component:**
- Added Terms & Conditions checkbox with proper English text
- Improved button and input styles for better UX
- Ensured responsive layout and consistent colors
**Frontend / SignIn Component:**
- Updated button colors and hover effects
- Improved styling for 'Sign Up' link
**Frontend / Profile Component:**
- Added 'Generate Token' button for creating API tokens
- Displayed `student` and `experience` fields
- Improved layout and …
> feat: update user model, validation, SignUp, SignIn, and Profile components

- frontend/src/components/apiDocs/apiDocsEarthquakes.jsx
- frontend/src/components/hero/hero.jsx
- frontend/src/components/info/info.jsx
- frontend/src/components/navbar/navbarMenu.jsx
This pull request improves the UI across multiple pages by updating button colors and applying the `rounded-full` style to ensure a cleaner and more consistent design.
- Updated button color scheme for better visual consistency
- Applied `rounded-full` styling to buttons on several pages
- Improved overall look and feel for a modern UI experience
- No breaking changes introduced
- This PR focuses only on UI style improvements
> style: update button colors and apply rounded-full on multiple pages

- frontend/src/components/apiDocs/apiDocsEarthquakes.jsx
- frontend/src/components/footer/footer.jsx
- frontend/src/components/hero/hero.jsx
- frontend/src/components/info/info.jsx
- frontend/src/components/navbar/navbarMenu.jsx
- frontend/src/pages/auth/forgotPassword.jsx
- frontend/src/pages/auth/resetPassword.jsx
- frontend/src/pages/auth/signIn.jsx
- frontend/src/pages/auth/signUp.jsx
- frontend/src/pages/noPage/noPage.jsx
- frontend/src/pages/profile/profile.jsx
This PR improves the accessibility of the frontend by adding appropriate aria-label attributes to all buttons, links, and anchor elements.
**Changes included:**
- Added aria-labels to all main navigation links (Home, About, Contact, etc.)
- Added aria-labels to buttons (Login, Logout, Sign Up, Delete Profile, Toggle Password Visibility, etc.)
- Added aria-labels to external links (GitHub, X/Twitter, LinkedIn)
- Ensured consistency and clarity for screen reader users
**Expected Behavior:**
All interactive elements now have descriptive aria-labels, improving accessibility for visually impaired users.
> Add aria-labels to buttons, links, and hrefs

- README.md
- backend/README.md
- frontend/README.md
Update Documentation and Licensing in README.md
> docs: Update Documentation and Licensing in README.md

- backend/src/middleware/rateLimiter.js
- frontend/src/components/navbar/navbarMenu.jsx
Update rate limiter configuration and enhance navbar styling for better user experience
> Update rate limiter configuration and enhance navbar styling

- backend/src/controllers/githubController.js
This PR refactors the GitHub authentication flow to improve environment handling, streamline redirects, and enhance error handling.
**Changes include:**
- Environment-aware callback URL: Added dynamic selection of GitHub callback URL based on DEV_ENV to support both development and production environments.
- Updated githubAuthRoutes.js: Uses dynamic GITHUB_CALLBACK_URL instead of a static environment variable.
- Improved error handling: Added clearer error messages and status codes.
- Controller cleanup: Streamlined githubAuthController to reduce redundancy and improve readability.
- Environment variables: Added GITHUB_CALLBACK_URL_PROD and GITHUB_CALLBACK_URL_DEV for flexible deployment.
**Benefits:**
- Fixes 404 errors in production caused by incorrect callback URLs.
- …
> Refactor GitHub authentication controller: streamline redirect and error handling

- backend/package-lock.json
- frontend/src/pages/docs/docs.jsx
What’s New
-Replaced empty /docs page with a full documentation layout
-Added intro + getting started guide with sample request
-Documented authentication usage
-Added API Reference table with all endpoints + query params
-Included example request/response and response fields explained
-Added error codes + rate limits
-Added small FAQ section
> Added Docs Page

- frontend/src/pages/contact/contact.jsx
**Description**
This PR refactors the Contact page to improve both user experience and form handling.
Key improvements include:
✅ Implemented form validation using Yup and react-hook-form
✅ Added error messages for invalid or missing fields
✅ Enhanced UI/UX with loading state (spinner + disabled button while sending)
✅ Integrated SweetAlert2 for success and error feedback
✅ Applied responsive layout with grid to align Name + Lastname and Email + Subject on the same row (desktop view)
✅ Kept mobile-first design (inputs stack vertically on small screens)
✅ Improved overall code readability and maintainability
> Refactor Contact page: implement form validation with Yup, enhance UI with loading state and error handling

- frontend/src/pages/about/about.jsx
- frontend/src/pages/contact/contact.jsx
- frontend/src/pages/docs/docs.jsx
- frontend/src/pages/useCases/useCases.jsx
This pull request fixes JSX structural issues and improves formatting consistency in the following frontend components:
- About.jsx
- Contact.jsx
- Docs.jsx
- UseCases.jsx
**Changes**
- Fixed missing closing tags (</div>, </p>, etc.).
- Corrected improper .map() closures to avoid rendering errors.
- Ensured indentation and JSX hierarchy consistency.
- No logic or styling changes applied — only syntax and formatting fixes.
> Fix: corrected missing closing tags and map closures

- backend/src/controllers/authControllers.js
closes #187 
- Improved **code readability and structure**.  
- Standardized **error handling responses**.  
- Reduced redundancy in multiple controllers.  
- Ensured **password handling & validation** flows remain clear.  
- Maintained **all existing functionality intact**.  
- More maintainable authentication logic.  
- Cleaner developer experience.  
- Future-proof for adding features like email verification & OAuth.
> Optimized Authentication Controllers (authControllers.js)

- frontend/src/pages/useCases/useCases.jsx
@nagcas, I have added the third use case - Civil Protection Application. Kindly review and merge the PR.
> Added Civil Use Case

- frontend/src/App.jsx
- frontend/src/components/footer/footer.jsx
- frontend/src/components/newsletter/Newsletter.jsx
- frontend/src/pages/home/home.jsx
**Summary**  
This PR introduces several small but impactful UI refinements:  
**Changes Made**  
- Newsletter component now appears only on the Home page (removed from global scope).  
- Background removed from the newsletter section for a cleaner, more minimal look.  
- Rounded buttons and inline form styling aligned with the overall page design.  
- Footer adjusted for better consistency and spacing.  
- Social icons improved for clarity and alignment.  
**Impact**  
These adjustments ensure a more consistent design, reduce visual clutter, and keep the Newsletter section contextually relevant to the Home page only.
> Refactor UI Improvements: Newsletter & Footer Refinements

- backend/src/app.js
**Changes made:**
- Registered /auth/github and /auth/github/callback inside app.js
- Applied cors(corsAuthOptions) to allow secure frontend requests
- Integrated GitHub strategy with existing authentication flow
> fix: add GitHub login route to app entrypoint

- backend/src/app.js
Fix CORS configuration and environment handling
- Updated CORS settings to allow frontend origins in both development and production.
- Added separate CORS options for authenticated and public routes.
- Ensured `/v1/earthquakes` remains public while securing other endpoints.
- Fixed CORS issues causing blocked requests in production.
> Fix CORS configuration and environment handling

- frontend/src/components/footer/footer.jsx
This PR updates the footer component to improve navigation structure, accessibility, and code maintainability.
**Changes Made:**
- Replaced <a> with NavLink for internal navigation.
- Added a gradient divider under the project name.
- Moved Terms & Conditions and Privacy Policy into a dedicated "Resources" menu.
- Improved accessibility with aria-label attributes.
- Adjusted layout with Tailwind for better responsiveness.
> Refactor footer with NavLink, Terms & Privacy separation

- frontend/src/pages/useCases/useCases.jsx
Hey @nagcas, please review and merge. I have added the educational use case.
> Added Education and Learning Use Case

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.jsx
This PR integrates Vercel Analytics into the TerraQuake project.
- Added <Analytics /> component to the main app layout.
- Enables tracking and analysis of user interactions across the application.
- Follows Vercel Analytics documentation for proper implementation.
**Changes:**
- Imported Analytics from @vercel/analytics/next.
- Added <Analytics /> to the main layout component.
> Integrate Vercel Analytics into App Layout

- backend/package-lock.json
- backend/package.json
- backend/src/app.js
This PR improves the security of the TerraQuake API by adding key middleware:
- express-mongo-sanitize → prevents NoSQL injection in MongoDB queries.
- xss-clean → mitigates XSS attacks by sanitizing user input.
- hpp → prevents HTTP Parameter Pollution.
These changes strengthen input handling and reduce attack surfaces while keeping public endpoints functional.
> Title: Enhance API Security with Middleware

- frontend/src/components/FAQ/FAQ.jsx
- frontend/src/pages/about/about.jsx
- frontend/src/pages/apiAccess/apiAccess.jsx
- frontend/src/pages/auth/changePassword.jsx
- frontend/src/pages/auth/forgotPassword.jsx
- frontend/src/pages/auth/githubAuth.jsx
- frontend/src/pages/auth/resetPassword.jsx
- frontend/src/pages/auth/signIn.jsx
- frontend/src/pages/auth/signUp.jsx
- frontend/src/pages/blog/BlogPost.jsx
- frontend/src/pages/blog/blog.jsx
- frontend/src/pages/blog/blogDetail.jsx
- frontend/src/pages/contact/contact.jsx
- frontend/src/pages/contribute/contribute.jsx
- frontend/src/pages/docs/docs.jsx
- frontend/src/pages/exploreData/exploreData.jsx
- frontend/src/pages/home/home.jsx
- frontend/src/pages/noPage/metaData.jsx
- frontend/src/pages/noPage/noPage.jsx
- frontend/src/pages/privacyPolicy/privacyPolicy.jsx
- frontend/src/pages/profile/deleteProfile.jsx
- frontend/src/pages/profile/editProfile.jsx
- frontend/src/pages/profile/profile.jsx
- frontend/src/pages/termsAndConditions/termsAndConditions.jsx
This PR improves the SEO metadata for the FAQ page of the TerraQuake API project. 
Changes include:  
- Added detailed `description`, `ogDescription`, and `twitterDescription` fields.  
- Added targeted SEO keywords.  
- Structured metadata consistently with other pages for better SEO performance.  
These changes help improve search visibility and ensure consistent SEO across the site.
> Enhance SEO metadata for FAQ page

- frontend/src/components/FAQ/FAQ.jsx
- frontend/src/components/utils/backToTopButton.jsx
- frontend/src/pages/about/about.jsx
- frontend/src/pages/apiAccess/apiAccess.jsx
- frontend/src/pages/auth/changePassword.jsx
- frontend/src/pages/auth/forgotPassword.jsx
- frontend/src/pages/auth/resetPassword.jsx
- frontend/src/pages/auth/signIn.jsx
- frontend/src/pages/auth/signUp.jsx
- frontend/src/pages/blog/blog.jsx
- frontend/src/pages/blog/blogDetail.jsx
- frontend/src/pages/contact/contact.jsx
- frontend/src/pages/contribute/contribute.jsx
- frontend/src/pages/docs/docs.jsx
- frontend/src/pages/exploreData/exploreData.jsx
- frontend/src/pages/home/home.jsx
- frontend/src/pages/privacyPolicy/privacyPolicy.jsx
- frontend/src/pages/profile/profile.jsx
- frontend/src/pages/termsAndConditions/termsAndConditions.jsx
- frontend/src/pages/useCases/useCases.jsx
This PR introduces a reusable BackToTopButton component and integrates it across all main pages of the application.
Changes:
- Created BackToTopButton component with smooth scrolling and responsive design.
- Added BackToTopButton to all relevant pages for consistent user experience.
- Removed redundant button code from individual pages.
Benefits:
- Improves code reusability and maintainability.
- Enhances navigation across the site.
- Provides a consistent UI/UX for all users.
> feat(global): add reusable BackToTopButton component and integrate

- frontend/src/components/apiPlayground/ApiPlayground.jsx
- frontend/src/pages/exploreData/exploreData.jsx
Titolo PR:
Refactor style for Explore Data page and API Playground
Descrizione PR:
This PR improves the structure and styling of the Explore Data page and the API Playground component for better readability, maintainability, and visual consistency.
> refactor style ui

- frontend/src/components/FAQ/FAQ.jsx
- frontend/src/pages/about/about.jsx
- frontend/src/pages/apiAccess/apiAccess.jsx
- frontend/src/pages/blog/blog.jsx
- frontend/src/pages/contact/contact.jsx
- frontend/src/pages/docs/docs.jsx
- frontend/src/pages/privacyPolicy/privacyPolicy.jsx
- frontend/src/pages/termsAndConditions/termsAndConditions.jsx
This PR introduces style improvements to the "Documentation" and "Explore Data" pages to enhance visual consistency and user experience.
Main changes:
- Unified styling for main titles across pages.
- Improved motion animations for header sections.
- Enhanced readability and layout structure.
- Updated markup for consistent design throughout the project.
> Refactor: Uniform style for titles and motion effects in Docs and Explore Data pages

- frontend/src/pages/auth/signIn.jsx
**Description**
This PR refactors the page style to align with the design and layout used on the Contact page.
The update ensures a cohesive and professional look across the entire TerraQuake API website, maintaining consistency in typography, color scheme, and motion effects.
**Changes Made**
- Adjusted typography and heading hierarchy to match the Contact page style.
- Applied consistent spacing, padding, and section layout.
- Unified button and link design (gradients, hover effects, rounded corners).
- Updated Framer Motion animations for smoother and more natural transitions.
- Enhanced alignment and responsiveness on mobile and desktop.
> refactor: updated page style to match Contact page design

- frontend/src/pages/auth/githubAuth.jsx
- Added a full-screen loading spinner for GitHub authentication.
- Improved error handling with fallback messages.
- Ensured proper navigation if token is missing or invalid.
- Made spinner visually centered with gradient background for better UX.
> feat(auth): improve GitHub login flow with centered spinner
